# Generated by Django 4.2 on 2024-01-01 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('acceleration', models.IntegerField()),
                ('power', models.IntegerField()),
                ('type', models.CharField(choices=[('petrol', 'petrol'), ('electricity', 'electricity'), ('gasoline', 'gasoline')], default='petrol', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('kilometer', models.IntegerField()),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=20)),
                ('posting_time', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 16, 34, 0, 816663), editable=False)),
                ('picture', models.ImageField(upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.car')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.seller')),
            ],
        ),
    ]
