# Generated by Django 4.2 on 2024-01-01 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='type',
            field=models.CharField(choices=[('shakhsi', 'shakhsi'), ('bongah', 'bongah'), ('namayeshgah', 'namayeshgah')], default='shakhsi', max_length=50),
        ),
        migrations.AlterField(
            model_name='ads',
            name='posting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 16, 53, 21, 565804), editable=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='acceleration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.brand'),
        ),
    ]
