# Generated by Django 4.2 on 2024-01-01 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_brand_seller_type_alter_ads_posting_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='posting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 16, 53, 27, 102367), editable=False),
        ),
    ]
