# Generated by Django 4.2 on 2024-01-01 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ads_picture_alter_ads_posting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.PositiveIntegerField(default=1000000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ads',
            name='posting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 17, 9, 34, 743244), editable=False),
        ),
    ]
