# Generated by Django 4.2 on 2024-01-01 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ads_price_alter_ads_posting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='picture',
            field=models.ImageField(blank=True, default='./media/assets/img/default-car.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='ads',
            name='posting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 17, 36, 47, 616072), editable=False),
        ),
    ]
