# Generated by Django 4.2 on 2024-01-01 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ads_picture_alter_ads_posting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='picture',
        ),
        migrations.AlterField(
            model_name='ads',
            name='posting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 17, 43, 59, 273260), editable=False),
        ),
    ]
