# Generated by Django 4.2 on 2024-01-01 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_ads_picture_alter_ads_posting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('petrol', 'petrol'), ('electricity', 'electricity'), ('gasoline', 'gasoline')], default='petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='posting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 18, 11, 24, 125020), editable=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('car', 'car'), ('bicycle', 'bicycle'), ('motor', 'motor'), ('heavy_car', 'heavy_car')], default='car', max_length=20),
        ),
    ]
