# Generated by Django 4.2 on 2024-01-03 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_ads_nardebam_alter_ads_posting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(default=9111111111, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ads',
            name='posting_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 21, 1, 43, 184621), editable=False),
        ),
    ]
